github_pages:
  path: benchmarks

storage:
  measurements_capacity: 5

units:
  - name: allocs/op
    better: lower
    threshold: 0.05

  - name: B/op
    better: lower
    threshold: 0.1

  - name: ns/op
    better: lower
    threshold: 0.1

  - name: iterations
    better: higher
    threshold: 0.1
